### ISSUE TITLE
:arrow_forward: Google Play Console report IllegalStateException

### ISSUE THREAD

**Issue by Cynnexis** [Cynnexis/tide#40]
**Describe the bug**
When creating a release for Tide [`v1.0.0`](https://github.com/Cynnexis/tide/releases/tag/v1.0.0), the Google Play Console reports the following error:

```java
FATAL EXCEPTION: main
Process: jp.co.sharp.android.iwnnime.ml, PID: 7472
java.lang.RuntimeException: Unable to start receiver jp.co.sharp.android.iwnnime.ml.DecoEmojiListener: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=jp.co.omronsoft.android.decoemojimanager_docomo/.DecoEmojiManager }: app is in background uid null
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3521)
	at android.app.ActivityThread.access$1400(ActivityThread.java:209)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1753)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6846)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=jp.co.omronsoft.android.decoemojimanager_docomo/.DecoEmojiManager }: app is in background uid null
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at jp.co.sharp.android.iwnnime.ml.DecoEmojiListener.updateConfirm(DecoEmojiListener.java:211)
	at jp.co.sharp.android.iwnnime.ml.DecoEmojiListener.onReceive(DecoEmojiListener.java:184)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3508)
	... 8 more
```

**Expected behavior**
No error in the Google Play Console.

**Smartphone (please complete the following information):**
 - Model name: AQUOS sense2 SH-01L
 - Manufacturer: Sharp
 - Android version: Android 9 (SDK 28)
 - Locale: en_US
 - Screen size: 1080 x 2160
 - Screen density (DPI): 480
 - RAM (total memory): 3,072 MB
 - OpenGL ES version: 3.2
 - ABI: ARM64_V8
 - CPU: Qualcomm SDM450

**Screenshots**

![Screenshot of the Google Play Page. All texts were already described in this issue.](https://user-images.githubusercontent.com/2932967/163705065-d3e81b78-bb26-4043-8ee5-47ab8dcc6301.png)

**Additional context**
Here is a video of the testing that caused the error:

[video](https://storage.googleapis.com/play-mtaas-results-prod/org.tide.app/1/SH-01L-28-en_US-portrait/video.mp4?GoogleAccessId=498997737111-pmn4sf5896c460sheh5fv3k1j1cq46t5@developer.gserviceaccount.com&Expires=1650181700&Signature=KwnDGxPQaDgwdRASSM1EdN7inuJErSJUY5CYLXv1v/zGj4jv/GSaKxdTLKgIRNJrlPgiDQSqYsS%2BFgDGLkRtX7WOVFyyAQtLuM4SVnnlEXtzkgvJpQNIBdUpj5CxX/NCZ/X%2BdIMX%2Bf6bGskQm8BmdDPgRVLxvsNcMErbcYazampwRLb3SlQ9m6s7uS9hvAoO9zCd/DXIkuhFcPls0EhhaGndsjNXT2PpE0pCLOzYsSoEyE9h%2B69oovmMgM6kh26e5V8Xhs%2B/6dd2E7eQMK86U2fZmwMjrEz5BmqAtwEKC5ylYtJ1IDsmGLVNKNmLM53VsZoZbJA/FkglQQAFZHF/XA%3D%3D)

**Comment by MRami153** [comment]
Hello any update on this ?
